In [2]:
!pip install gym
import numpy as np
import gym

     ---------------------------------------- 0.0/721.7 kB ? eta -:--:--
     ---------- --------------------------- 194.6/721.7 kB 5.9 MB/s eta 0:00:01
     ----------------------- -------------- 440.3/721.7 kB 4.6 MB/s eta 0:00:01
     -------------------------------------  716.8/721.7 kB 5.0 MB/s eta 0:00:01
     -------------------------------------  716.8/721.7 kB 5.0 MB/s eta 0:00:01
     -------------------------------------- 721.7/721.7 kB 3.0 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for gym: filename=gym-0.26.2-py3-none-any.whl size=827630 sha256=66c142658df7c059f5c971f4787106e4a27176487efe400873ecd59b89477fdf
  Stored in directory: c:\users\pi\appdata\local\pi


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
env = gym.make("FrozenLake-v1")
n_observations = env.observation_space.n
n_actions = env.action_space.n

In [6]:
#Initialize the Q-table to 0
Q_table = np.zeros((n_observations,n_actions))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
